"""
Copy Agent — writes concise Email A, Instagram DM, Follow-Up 1 & 2 for HOT leads.
No Email B generated by default (reduces tokens; B is a manual variation).
"""

import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config.lumus_config import AGENCY_EMAIL, AGENCY_WEBSITE


def _email_a(name, sector, location, angle, service):
    return (
        f"Subject: {name} — one thing costing you customers right now\n\n"
        f"Hi,\n\n"
        f"I was looking at {sector.lower()}s in {location} and came across {name}.\n\n"
        f"{angle}.\n\n"
        f"At Lumus we help local businesses fix this quickly — no jargon, no long contracts. "
        f"Specifically, we'd sort your {service.lower()} within a few weeks.\n\n"
        f"Worth a quick 15-minute call?\n\n"
        f"— Lumus\n{AGENCY_EMAIL} | {AGENCY_WEBSITE}"
    )


def _instagram_dm(name, sector, location, service):
    return (
        f"Hi! Came across {name} — love what you're doing.\n\n"
        f"Quick question: have you sorted your {service.lower()} yet? "
        f"A lot of {sector.lower()}s in {location} are missing customers because of this.\n\n"
        f"Happy to share a couple of ideas — no strings. — Lumus 🌟"
    )


def _follow_up_1(name, service):
    return (
        f"Subject: Re: {name} — just checking in\n\n"
        f"Hi,\n\n"
        f"Sent a note last week about {service.lower()} for {name} — "
        f"just following up in case it got buried.\n\n"
        f"Happy to send a free one-page audit if that's easier. Just say the word.\n\n"
        f"— Lumus\n{AGENCY_EMAIL}"
    )


def _follow_up_2(name, service):
    return (
        f"Subject: Last one from me — {name}\n\n"
        f"Hi,\n\nThis is my last message — don't want to be a nuisance.\n\n"
        f"If {name} ever needs help with {service.lower()}, we're here.\n\n"
        f"Wishing you a great week.\n— Lumus\n{AGENCY_EMAIL}"
    )


def run(leads: list[dict]) -> list[dict]:
    for lead in leads:
        name = lead.get("Business Name", "your business")
        sector = lead.get("Sector", "local business")
        location = lead.get("Location", "your area")
        angle = lead.get("Outreach Angle", "Your digital presence could be stronger")
        service = lead.get("Recommended Lumus Service", "digital presence")

        lead["Email Version A"] = _email_a(name, sector, location, angle, service)
        lead["Email Version B"] = ""   # Reserved for manual variation
        lead["Instagram DM"] = _instagram_dm(name, sector, location, service)
        lead["Follow-Up 1"] = _follow_up_1(name, service)
        lead["Follow-Up 2"] = _follow_up_2(name, service)
        print(f"  [copy] Wrote outreach for: {name}")

    print(f"[copy] {len(leads)} outreach sets generated")
    return leads
